export const MOSTRAR_PRODUCTOS = 'MOSTRAR_PRODUCTOS';
export const MOSTRAR_PRODUCTO = 'MOSTRAR_PRODUCTO';
export const AGREGAR_PRODUCTO = 'AGREGAR_PRODUCTO';
export const EDITAR_PRODUCTO = 'EDITAR_PRODUCTO';
export const ELIMINAR_PRODUCTO = 'ELIMINAR_PRODUCTO';